const strings = {
  nav: {
    home: "Home",
    login: "Login",
    adminLogin: "Admin Login",
    dashboard: "Dashboard",
    clients: "Clients",
    trucks: "Trucks",
    workers: "Workers",
    products: "Products",
    orders: "Orders",
    logout: "Logout",
    register: "Register",
    myAccount: "My Account",
    clientDashboard: "Dashboard",
    purchaseHistory: "Purchase History",
    placeOrder: "Place Order",
    claims: "Claims",
  },
  home: {
    title: "CompTech Pro",
    subtitle: "Enterprise B2B Component Solutions",
    heroDescription:
      "Your trusted partner for high-quality computer components. Streamline your procurement, manage your fleet, and scale your business with our all-in-one platform.",
    getStarted: "Get Started",
    learnMore: "Learn More",
  },
  login: {
    title: "Client Login",
    emailLabel: "Email",
    passwordLabel: "Password",
    submitButton: "Sign In",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
    invalidCredentials: "Invalid email or password. Please try again.",
    welcomeBack: "Welcome back!",
  },
  register: {
    title: "Create Account",
    subtitle: "Register your company to start ordering",
    nameLabel: "Full Name",
    emailLabel: "Email",
    companyName: "Company Name",
    location: "Location",
    idNumber: "Tax ID / NIF",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    submitButton: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign in",
    successMessage: "Account created successfully! Redirecting to login...",
    passwordMismatch: "Passwords do not match",
    emailTaken: "This email is already registered",
  },
  admin: {
    loginTitle: "Admin Login",
    emailLabel: "Email",
    passwordLabel: "Password",
    submitButton: "Sign In",
    invalidCredentials: "Invalid admin credentials. Please try again.",
    welcomeBack: "Welcome back, Admin!",
    dashboardTitle: "Admin Dashboard",
    clientsTitle: "Client Management",
    trucksTitle: "Truck Fleet Management",
    workersTitle: "Worker Management",
  },
  dashboard: {
    totalRevenue: "Total Revenue",
    activeClients: "Active Clients",
    availableTrucks: "Available Trucks",
    activeWorkers: "Active Workers",
    monthlyRevenue: "Monthly Revenue",
    quarterlyRevenue: "Quarterly Revenue",
    yearlyRevenue: "Yearly Revenue",
    totalSales: "Total Sales",
    lastMonth: "Last Month",
    last3Months: "Last 3 Months",
    last6Months: "Last 6 Months",
    lastYear: "Last Year",
    allTime: "All Time",
    revenueOverview: "Revenue Overview",
    quickActions: "Quick Actions",
    recentActivity: "Recent Activity",
  },
  clients: {
    title: "Client Management",
    addClient: "Add Client",
    editClient: "Edit Client",
    deleteClient: "Delete Client",
    clientName: "Client Name",
    email: "Email",
    location: "Location",
    idNumber: "ID Number",
    activationDate: "Activation Date",
    totalPurchases: "Total Purchases",
    lastMonthPurchases: "Last Month",
    last3MonthsPurchases: "Last 3 Months",
    last6MonthsPurchases: "Last 6 Months",
    lastYearPurchases: "Last Year",
    commonProducts: "Common Products",
    productType: "Product Type",
    quantity: "Quantity",
    frequency: "Frequency",
    noClients: "No clients found",
    confirmDelete: "Are you sure you want to delete this client?",
    clientDeleted: "Client deleted successfully",
    clientAdded: "Client added successfully",
    clientUpdated: "Client updated successfully",
  },
  trucks: {
    title: "Truck Fleet Management",
    addTruck: "Add Truck",
    editTruck: "Edit Truck",
    deleteTruck: "Delete Truck",
    plateNumber: "Plate Number",
    model: "Model",
    capacity: "Capacity",
    kilometrage: "Kilometrage",
    status: "Status",
    available: "Available",
    loading: "Loading",
    shipping: "Shipping",
    returning: "Returning",
    underRepair: "Under Repair",
    disabled: "Disabled",
    markAsAvailable: "Mark as Available",
    markAsLoading: "Mark as Loading",
    markAsRepair: "Mark as Under Repair",
    markAsDisabled: "Mark as Disabled",
    availableCapacity: "Avail. Capacity",
    destination: "Destination",
    driver: "Driver",
    shipTruck: "Ship Truck",
    returnTruck: "Register Return",
    newKilometrage: "New Kilometrage",
    selectDriver: "Select Driver",
    selectTruck: "Select Truck for Order",
    noDriversAvailable: "No drivers available",
    noTrucks: "No trucks registered",
    confirmDelete: "Are you sure you want to delete this truck?",
    truckAdded: "Truck added successfully",
    truckUpdated: "Truck updated successfully",
    truckDeleted: "Truck deleted successfully",
    capacityUnit: "kg",
  },
  workers: {
    title: "Worker Management",
    addWorker: "Add Worker",
    editWorker: "Edit Worker",
    deleteWorker: "Delete Worker",
    workerName: "Worker Name",
    position: "Position",
    startDate: "Start Date",
    status: "Status",
    available: "Available",
    driving: "Driving",
    onVacation: "On Vacation",
    sickLeave: "Sick Leave",
    inactive: "Inactive",
    markAvailable: "Mark as Available",
    markDriving: "Mark as Driving",
    markVacation: "Mark as On Vacation",
    markSick: "Mark as Sick Leave",
    markInactive: "Mark as Inactive",
    noWorkers: "No workers registered",
    confirmDelete: "Are you sure you want to delete this worker?",
    workerAdded: "Worker added successfully",
    workerUpdated: "Worker updated successfully",
    workerDeleted: "Worker deleted successfully",
  },
  products: {
    title: "Product Management",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    deleteProduct: "Delete Product",
    productName: "Product Name",
    brand: "Brand",
    type: "Type",
    price: "Price",
    weight: "Weight (kg)",
    active: "Active",
    inactive: "Inactive",
    enableProduct: "Enable Product",
    disableProduct: "Disable Product",
    noProducts: "No products registered",
    confirmDelete: "Are you sure you want to delete this product?",
    productAdded: "Product added successfully",
    productUpdated: "Product updated successfully",
    productDeleted: "Product deleted successfully",
    productTypes: [
      "CPU",
      "GPU",
      "RAM",
      "Storage",
      "Motherboard",
      "PSU",
      "Cooling",
      "Other",
    ],
  },
  orders: {
    title: "Orders",
    placeOrder: "Place New Order",
    orderHistory: "Order History",
    orderId: "Order ID",
    orderDate: "Date",
    status: "Status",
    totalAmount: "Total Amount",
    items: "Items",
    quantity: "Quantity",
    unitPrice: "Unit Price",
    estimatedDelivery: "Est. Delivery",
    deliveryAddress: "Delivery Address",
    deliveryAddressPlaceholder: "Street, city, postal code, country...",
    noOrders: "No orders found",
    pendingApproval: "Pending Approval",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    selectProduct: "Select Product",
    productNotAvailable: "Product not available",
    submitOrder: "Submit Order",
    orderPlaced: "Order placed successfully!",
    orderConfirmed: "Order confirmed",
    deliveryDateSet: "Delivery date set",
    confirmCancel: "Are you sure you want to cancel this order?",
    cancelOrder: "Cancel Order",
    markAsDelivered: "Mark as Delivered",
    addToOrder: "Add to Order",
    remove: "Remove",
    currentOrder: "Current Order",
    newOrder: "New Order",
    activeOrders: "Active Orders",
    total: "Total",
    submitOrderConfirm: "Submit this order?",
    chooseProducts: "Choose products and quantities",
    adminNoteLabel: "Message to client",
    adminNotePlaceholder: "e.g. Delayed due to production of X component...",
  },
  claims: {
    title: "Claims",
    fileClaim: "File a Claim",
    editClaim: "Edit Claim",
    claimId: "Claim ID",
    orderId: "Order",
    product: "Product",
    reason: "Reason",
    description: "Description",
    status: "Status",
    resolution: "Resolution",
    pending: "Pending",
    inProcess: "In Process",
    approved: "Approved",
    refused: "Refused",
    noClaims: "No claims filed",
    reasonLabel: "Reason for Claim",
    descriptionLabel: "Detailed Description",
    submitClaim: "Submit Claim",
    claimFiled: "Claim filed successfully!",
    claimUnderReview: "Your claim is under review",
    claimResolved: "Claim resolved",
    selectOrder: "Select Order",
    selectProduct: "Select Product",
    confirmResolution: "Resolution",
    myClaims: "My Claims",
  },
  client: {
    dashboardTitle: "Client Dashboard",
    welcomeMessage: "Welcome back",
    totalOrders: "Total Orders",
    pendingOrders: "Pending Orders",
    approvedOrders: "Confirmed Orders",
    totalSpent: "Total Spent",
    activeClaims: "Active Claims",
    recentOrders: "Recent Orders",
    quickOrder: "Quick Order",
    viewHistory: "View History",
    latestClaim: "Latest Claim",
    myProfile: "My Profile",
  },
  common: {
    loading: "Loading...",
    error: "Something went wrong",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    search: "Search",
    filter: "Filter",
    all: "All",
    actions: "Actions",
    confirm: "Confirm",
    success: "Success",
    warning: "Warning",
    info: "Info",
    yes: "Yes",
    no: "No",
    back: "Back",
    next: "Next",
    submit: "Submit",
    reset: "Reset",
    noResults: "No results found",
    pageNotFound: "Page not found",
    goHome: "Go to Home",
    currencySymbol: "€",
    required: "Required",
    optional: "Optional",
    status: "Status",
    register: "Register",
    signIn: "Sign In",
    newer: "Newer",
    older: "Older",
    today: "Today",
    yesterday: "Yesterday",
  },
} as const;

export default strings;
export type Strings = typeof strings;
