const strings = {
  nav: {
    home: "Inicio",
    login: "Iniciar Sesión",
    adminLogin: "Admin",
    dashboard: "Panel",
    clients: "Clientes",
    trucks: "Camiones",
    workers: "Trabajadores",
    products: "Productos",
    orders: "Pedidos",
    logout: "Cerrar Sesión",
    register: "Registrarse",
    myAccount: "Mi Cuenta",
    clientDashboard: "Panel de Cliente",
    purchaseHistory: "Historial de Compras",
    placeOrder: "Realizar Pedido",
    claims: "Reclamaciones",
  },
  home: {
    title: "CompTech Pro",
    subtitle: "Soluciones B2B para Componentes",
    heroDescription:
      "Tu socio de confianza para componentes de ordenador de alta calidad. Optimiza tus compras, gestiona tu flota y escala tu negocio con nuestra plataforma integral.",
    getStarted: "Comenzar",
    learnMore: "Más Información",
  },
  login: {
    title: "Inicio de Sesión",
    emailLabel: "Correo Electrónico",
    passwordLabel: "Contraseña",
    submitButton: "Iniciar Sesión",
    forgotPassword: "¿Olvidaste tu contraseña?",
    noAccount: "¿No tienes cuenta?",
    signUp: "Registrarse",
    invalidCredentials: "Correo o contraseña inválidos. Inténtalo de nuevo.",
    welcomeBack: "¡Bienvenido de nuevo!",
  },
  register: {
    title: "Crear Cuenta",
    subtitle: "Registra tu empresa para empezar a pedir",
    nameLabel: "Nombre Completo",
    emailLabel: "Correo Electrónico",
    companyName: "Nombre de la Empresa",
    location: "Ubicación",
    idNumber: "NIF/CIF",
    passwordLabel: "Contraseña",
    confirmPasswordLabel: "Confirmar Contraseña",
    submitButton: "Crear Cuenta",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    signIn: "Iniciar Sesión",
    successMessage:
      "¡Cuenta creada correctamente! Redirigiendo al inicio de sesión...",
    passwordMismatch: "Las contraseñas no coinciden",
    emailTaken: "Este correo ya está registrado",
  },
  admin: {
    loginTitle: "Acceso de Administrador",
    emailLabel: "Correo Electrónico",
    passwordLabel: "Contraseña",
    submitButton: "Iniciar Sesión",
    invalidCredentials: "Credenciales de administrador inválidas.",
    welcomeBack: "¡Bienvenido de nuevo, Admin!",
    dashboardTitle: "Panel de Administración",
    clientsTitle: "Gestión de Clientes",
    trucksTitle: "Gestión de Flota",
    workersTitle: "Gestión de Trabajadores",
  },
  dashboard: {
    totalRevenue: "Ingresos Totales",
    activeClients: "Clientes Activos",
    availableTrucks: "Camiones Disponibles",
    activeWorkers: "Trabajadores Activos",
    monthlyRevenue: "Ingresos Mensuales",
    quarterlyRevenue: "Ingresos Trimestrales",
    yearlyRevenue: "Ingresos Anuales",
    totalSales: "Ventas Totales",
    lastMonth: "Último Mes",
    last3Months: "Últimos 3 Meses",
    last6Months: "Últimos 6 Meses",
    lastYear: "Último Año",
    allTime: "Total Histórico",
    revenueOverview: "Resumen de Ingresos",
    quickActions: "Acciones Rápidas",
    recentActivity: "Actividad Reciente",
  },
  clients: {
    title: "Gestión de Clientes",
    addClient: "Añadir Cliente",
    editClient: "Editar Cliente",
    deleteClient: "Eliminar Cliente",
    clientName: "Nombre del Cliente",
    email: "Correo Electrónico",
    location: "Ubicación",
    idNumber: "NIF/CIF",
    activationDate: "Fecha de Activación",
    totalPurchases: "Compras Totales",
    lastMonthPurchases: "Último Mes",
    last3MonthsPurchases: "Últimos 3 Meses",
    last6MonthsPurchases: "Últimos 6 Meses",
    lastYearPurchases: "Último Año",
    commonProducts: "Productos Habituales",
    productType: "Tipo de Producto",
    quantity: "Cantidad",
    frequency: "Frecuencia",
    noClients: "No se encontraron clientes",
    confirmDelete: "¿Estás seguro de que quieres eliminar este cliente?",
    clientDeleted: "Cliente eliminado correctamente",
    clientAdded: "Cliente añadido correctamente",
    clientUpdated: "Cliente actualizado correctamente",
  },
  trucks: {
    title: "Gestión de Flota",
    addTruck: "Añadir Camión",
    editTruck: "Editar Camión",
    deleteTruck: "Eliminar Camión",
    plateNumber: "Matrícula",
    model: "Modelo",
    capacity: "Capacidad",
    kilometrage: "Kilometraje",
    status: "Estado",
    available: "Disponible",
    loading: "Cargando",
    shipping: "En Ruta",
    returning: "Regresando",
    underRepair: "En Reparación",
    disabled: "Inhabilitado",
    markAsAvailable: "Marcar como Disponible",
    markAsLoading: "Marcar como Cargando",
    markAsRepair: "Marcar como En Reparación",
    markAsDisabled: "Marcar como Inhabilitado",
    availableCapacity: "Cap. Disponible",
    destination: "Destino",
    driver: "Conductor",
    shipTruck: "Enviar Camión",
    returnTruck: "Registrar Regreso",
    newKilometrage: "Nuevo Kilometraje",
    selectDriver: "Seleccionar Conductor",
    selectTruck: "Seleccionar Camión para Pedido",
    noDriversAvailable: "No hay conductores disponibles",
    noTrucks: "No hay camiones registados",
    confirmDelete: "¿Estás seguro de que quieres eliminar este camión?",
    truckAdded: "Camión añadido correctamente",
    truckUpdated: "Camión actualizado correctamente",
    truckDeleted: "Camión eliminado correctamente",
    capacityUnit: "kg",
  },
  workers: {
    title: "Gestión de Trabajadores",
    addWorker: "Añadir Trabajador",
    editWorker: "Editar Trabajador",
    deleteWorker: "Eliminar Trabajador",
    workerName: "Nombre del Trabajador",
    position: "Puesto",
    startDate: "Fecha de Inicio",
    status: "Estado",
    available: "Disponible",
    driving: "Conduciendo",
    onVacation: "De Vacaciones",
    sickLeave: "Baja Médica",
    inactive: "Inactivo",
    markAvailable: "Marcar como Disponible",
    markDriving: "Marcar como Conduciendo",
    markVacation: "Marcar como Vacaciones",
    markSick: "Marcar como Baja Médica",
    markInactive: "Marcar como Inactivo",
    noWorkers: "No hay trabajadores registrados",
    confirmDelete: "¿Estás seguro de que quieres eliminar este trabajador?",
    workerAdded: "Trabajador añadido correctamente",
    workerUpdated: "Trabajador actualizado correctamente",
    workerDeleted: "Trabajador eliminado correctamente",
  },
  products: {
    title: "Gestión de Productos",
    addProduct: "Añadir Producto",
    editProduct: "Editar Producto",
    deleteProduct: "Eliminar Producto",
    productName: "Nombre del Producto",
    brand: "Marca",
    type: "Tipo",
    price: "Precio",
    weight: "Peso (kg)",
    active: "Activo",
    inactive: "Inactivo",
    enableProduct: "Activar Producto",
    disableProduct: "Desactivar Producto",
    noProducts: "No hay productos registrados",
    confirmDelete: "¿Estás seguro de que quieres eliminar este producto?",
    productAdded: "Producto añadido correctamente",
    productUpdated: "Producto actualizado correctamente",
    productDeleted: "Producto eliminado correctamente",
    productTypes: [
      "CPU",
      "GPU",
      "RAM",
      "Almacenamiento",
      "Placa Base",
      "Fuente",
      "Refrigeración",
      "Otro",
    ],
  },
  orders: {
    title: "Pedidos",
    placeOrder: "Realizar Nuevo Pedido",
    orderHistory: "Historial de Pedidos",
    orderId: "ID Pedido",
    orderDate: "Fecha",
    status: "Estado",
    totalAmount: "Importe Total",
    items: "Artículos",
    quantity: "Cantidad",
    unitPrice: "Precio Unit.",
    estimatedDelivery: "Entrega Est.",
    deliveryAddress: "Dirección de Entrega",
    deliveryAddressPlaceholder: "Calle, ciudad, código postal, país...",
    noOrders: "No se encontraron pedidos",
    pendingApproval: "Pendiente Aprobación",
    confirmed: "Confirmado",
    shipped: "Enviado",
    delivered: "Entregado",
    cancelled: "Cancelado",
    selectProduct: "Seleccionar Producto",
    productNotAvailable: "Producto no disponible",
    submitOrder: "Enviar Pedido",
    orderPlaced: "¡Pedido realizado con éxito!",
    orderConfirmed: "Pedido confirmado",
    deliveryDateSet: "Fecha de entrega establecida",
    confirmCancel: "¿Estás seguro de que quieres cancelar este pedido?",
    cancelOrder: "Cancelar Pedido",
    markAsDelivered: "Marcar como Entregado",
    addToOrder: "Añadir al Pedido",
    remove: "Eliminar",
    currentOrder: "Pedido Actual",
    newOrder: "Nuevo Pedido",
    activeOrders: "Pedidos Activos",
    total: "Total",
    submitOrderConfirm: "¿Enviar este pedido?",
    chooseProducts: "Elige productos y cantidades",
    adminNoteLabel: "Mensaje al cliente",
    adminNotePlaceholder: "Ej. Retrasado por producción del componente X...",
  },
  claims: {
    title: "Reclamaciones",
    fileClaim: "Presentar Reclamación",
    editClaim: "Editar Reclamación",
    claimId: "ID Reclamación",
    orderId: "Pedido",
    product: "Producto",
    reason: "Motivo",
    description: "Descripción",
    status: "Estado",
    resolution: "Resolución",
    pending: "Pendiente",
    inProcess: "En Proceso",
    approved: "Aprobada",
    refused: "Rechazada",
    noClaims: "No hay reclamaciones",
    reasonLabel: "Motivo de la Reclamación",
    descriptionLabel: "Descripción Detallada",
    submitClaim: "Enviar Reclamación",
    claimFiled: "¡Reclamación presentada con éxito!",
    claimUnderReview: "Tu reclamación está en revisión",
    claimResolved: "Reclamación resuelta",
    selectOrder: "Seleccionar Pedido",
    selectProduct: "Seleccionar Producto",
    confirmResolution: "Resolución",
    myClaims: "Mis Reclamaciones",
  },
  client: {
    dashboardTitle: "Panel del Cliente",
    welcomeMessage: "Bienvenido de nuevo",
    totalOrders: "Total Pedidos",
    pendingOrders: "Pedidos Pendientes",
    approvedOrders: "Pedidos Confirmados",
    totalSpent: "Total Gastado",
    activeClaims: "Reclamaciones Activas",
    recentOrders: "Pedidos Recientes",
    quickOrder: "Pedido Rápido",
    viewHistory: "Ver Historial",
    latestClaim: "Última Reclamación",
    myProfile: "Mi Perfil",
  },
  common: {
    loading: "Cargando...",
    error: "Algo salió mal",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    close: "Cerrar",
    search: "Buscar",
    filter: "Filtrar",
    all: "Todos",
    actions: "Acciones",
    confirm: "Confirmar",
    success: "Éxito",
    warning: "Aviso",
    info: "Información",
    yes: "Sí",
    no: "No",
    back: "Volver",
    next: "Siguiente",
    submit: "Enviar",
    reset: "Restablecer",
    noResults: "Sin resultados",
    pageNotFound: "Página no encontrada",
    goHome: "Ir al Inicio",
    currencySymbol: "€",
    required: "Obligatorio",
    optional: "Opcional",
    status: "Estado",
    register: "Registrarse",
    signIn: "Iniciar Sesión",
    newer: "Más recientes",
    older: "Más antiguos",
    today: "Hoy",
    yesterday: "Ayer",
  },
} as const;

export default strings;
export type Strings = typeof strings;
