const strings = {
  nav: {
    home: "Início",
    login: "Entrar",
    adminLogin: "Admin",
    dashboard: "Painel",
    clients: "Clientes",
    trucks: "Camides",
    workers: "Trabalhadores",
    products: "Produtos",
    orders: "Encomendas",
    logout: "Sair",
    register: "Registar",
    myAccount: "Minha Conta",
    clientDashboard: "Painel do Cliente",
    purchaseHistory: "Histórico de Compras",
    placeOrder: "Fazer Encomenda",
    claims: "Reclamações",
    auditLog: "Registo de Auditoria",
  },
  home: {
    title: "CompTech Pro",
    subtitle: "Soluções B2B para Componentes",
    heroDescription:
      "O teu parceiro de confiança para componentes de computador de alta qualidade. Otimiza as tuas compras, gere a tua frota e escala o teu negócio com a nossa plataforma completa.",
    getStarted: "Começar",
    learnMore: "Saber Mais",
  },
  login: {
    title: "Iniciar Sessão",
    emailLabel: "Email",
    passwordLabel: "Palavra-passe",
    submitButton: "Entrar",
    forgotPassword: "Esqueceste-te da palavra-passe?",
    noAccount: "Não tens conta?",
    signUp: "Registar",
    invalidCredentials: "Email ou palavra-passe inválidos. Tenta novamente.",
    welcomeBack: "Bem-vindo de volta!",
  },
  register: {
    title: "Criar Conta",
    subtitle: "Regista a tua empresa para começar a encomendar",
    nameLabel: "Nome Completo",
    emailLabel: "Email",
    companyName: "Nome da Empresa",
    location: "Localização",
    idNumber: "NIF",
    passwordLabel: "Palavra-passe",
    confirmPasswordLabel: "Confirmar Palavra-passe",
    submitButton: "Criar Conta",
    alreadyHaveAccount: "Já tens conta?",
    signIn: "Iniciar Sessão",
    successMessage: "Conta criada com sucesso! A redirecionar para o login...",
    passwordMismatch: "As palavras-passe não coincidem",
    emailTaken: "Este email já está registado",
  },
  admin: {
    loginTitle: "Acesso de Administrador",
    emailLabel: "Email",
    passwordLabel: "Palavra-passe",
    submitButton: "Entrar",
    invalidCredentials: "Credenciais de administrador inválidas.",
    welcomeBack: "Bem-vindo de volta, Admin!",
    dashboardTitle: "Painel de Administração",
    clientsTitle: "Gestão de Clientes",
    trucksTitle: "Gestão de Frota",
    workersTitle: "Gestão de Trabalhadores",
  },
  dashboard: {
    totalRevenue: "Receita Total",
    activeClients: "Clientes Ativos",
    availableTrucks: "Camides Disponíveis",
    activeWorkers: "Trabalhadores Ativos",
    monthlyRevenue: "Receita Mensal",
    quarterlyRevenue: "Receita Trimestral",
    yearlyRevenue: "Receita Anual",
    totalSales: "Vendas Totais",
    lastMonth: "Último Mês",
    last3Months: "Últimos 3 Meses",
    last6Months: "Últimos 6 Meses",
    lastYear: "Último Ano",
    allTime: "Total Histórico",
    revenueOverview: "Resumo de Receitas",
    quickActions: "Ações Rápidas",
    recentActivity: "Atividade Recente",
  },
  clients: {
    title: "Gestão de Clientes",
    addClient: "Adicionar Cliente",
    editClient: "Editar Cliente",
    deleteClient: "Eliminar Cliente",
    clientName: "Nome do Cliente",
    email: "Email",
    location: "Localização",
    idNumber: "NIF",
    activationDate: "Data de Ativação",
    totalPurchases: "Compras Totais",
    lastMonthPurchases: "Último Mês",
    last3MonthsPurchases: "Últimos 3 Meses",
    last6MonthsPurchases: "Últimos 6 Meses",
    lastYearPurchases: "Último Ano",
    commonProducts: "Produtos Habituais",
    productType: "Tipo de Produto",
    quantity: "Quantidade",
    frequency: "Frequência",
    noClients: "Nenhum cliente encontrado",
    confirmDelete: "Tens a certeza que queres eliminar este cliente?",
    clientDeleted: "Cliente eliminado com sucesso",
    clientAdded: "Cliente adicionado com sucesso",
    clientUpdated: "Cliente atualizado com sucesso",
  },
  trucks: {
    title: "Gestão de Frota",
    addTruck: "Adicionar Camide",
    editTruck: "Editar Camide",
    deleteTruck: "Eliminar Camide",
    plateNumber: "Matrícula",
    model: "Modelo",
    capacity: "Capacidade",
    kilometrage: "Quilometragem",
    status: "Estado",
    available: "Disponível",
    loading: "A Carregar",
    shipping: "Em Rota",
    returning: "A Regressar",
    underRepair: "Em Reparação",
    disabled: "Inativado",
    markAsAvailable: "Marcar como Disponível",
    markAsLoading: "Marcar como A Carregar",
    markAsRepair: "Marcar como Em Reparação",
    markAsDisabled: "Marcar como Inativado",
    availableCapacity: "Cap. Disponível",
    destination: "Destino",
    driver: "Motorista",
    shipTruck: "Enviar Camide",
    returnTruck: "Registar Regresso",
    newKilometrage: "Nova Quilometragem",
    selectDriver: "Selecionar Motorista",
    selectTruck: "Selecionar Camide para Encomenda",
    noDriversAvailable: "Nenhum motorista disponível",
    noTrucks: "Nenhum camide registado",
    confirmDelete: "Tens a certeza que queres eliminar este camide?",
    truckAdded: "Camide adicionado com sucesso",
    truckUpdated: "Camide atualizado com sucesso",
    truckDeleted: "Camide eliminado com sucesso",
    capacityUnit: "kg",
  },
  workers: {
    title: "Gestão de Trabalhadores",
    addWorker: "Adicionar Trabalhador",
    editWorker: "Editar Trabalhador",
    deleteWorker: "Eliminar Trabalhador",
    workerName: "Nome do Trabalhador",
    position: "Cargo",
    startDate: "Data de Início",
    status: "Estado",
    available: "Disponível",
    driving: "A Conduzir",
    onVacation: "De Férias",
    sickLeave: "Baixa Médica",
    inactive: "Inativo",
    markAvailable: "Marcar como Disponível",
    markDriving: "Marcar como A Conduzir",
    markVacation: "Marcar como Férias",
    markSick: "Marcar como Baixa Médica",
    markInactive: "Marcar como Inativo",
    noWorkers: "Nenhum trabalhador registado",
    confirmDelete: "Tens a certeza que queres eliminar este trabalhador?",
    workerAdded: "Trabalhador adicionado com sucesso",
    workerUpdated: "Trabalhador atualizado com sucesso",
    workerDeleted: "Trabalhador eliminado com sucesso",
  },
  products: {
    title: "Gestão de Produtos",
    addProduct: "Adicionar Produto",
    editProduct: "Editar Produto",
    deleteProduct: "Eliminar Produto",
    productName: "Nome do Produto",
    brand: "Marca",
    type: "Tipo",
    price: "Preço",
    weight: "Peso (kg)",
    active: "Ativo",
    inactive: "Inativo",
    enableProduct: "Ativar Produto",
    disableProduct: "Desativar Produto",
    noProducts: "Nenhum produto registado",
    confirmDelete: "Tens a certeza que queres eliminar este produto?",
    productAdded: "Produto adicionado com sucesso",
    productUpdated: "Produto atualizado com sucesso",
    productDeleted: "Produto eliminado com sucesso",
    productTypes: [
      "CPU",
      "GPU",
      "RAM",
      "Armazenamento",
      "Placa Mãe",
      "Fonte",
      "Arrefecimento",
      "Outro",
    ],
  },
  orders: {
    title: "Encomendas",
    placeOrder: "Nova Encomenda",
    orderHistory: "Histórico de Encomendas",
    orderId: "ID Encomenda",
    orderDate: "Data",
    status: "Estado",
    totalAmount: "Valor Total",
    items: "Itens",
    quantity: "Quantidade",
    unitPrice: "Preço Unit.",
    estimatedDelivery: "Entrega Est.",
    deliveryAddress: "Morada de Entrega",
    deliveryAddressPlaceholder: "Rua, cidade, código postal, país...",
    noOrders: "Nenhuma encomenda encontrada",
    pendingApproval: "Pendente Aprovação",
    confirmed: "Confirmada",
    shipped: "Enviada",
    delivered: "Entregue",
    cancelled: "Cancelada",
    selectProduct: "Selecionar Produto",
    productNotAvailable: "Produto não disponível",
    submitOrder: "Enviar Encomenda",
    orderPlaced: "Encomenda realizada com sucesso!",
    orderConfirmed: "Encomenda confirmada",
    deliveryDateSet: "Data de entrega definida",
    confirmCancel: "Tens a certeza que queres cancelar esta encomenda?",
    cancelOrder: "Cancelar Encomenda",
    markAsDelivered: "Marcar como Entregue",
    addToOrder: "Adicionar à Encomenda",
    remove: "Remover",
    currentOrder: "Encomenda Atual",
    newOrder: "Nova Encomenda",
    activeOrders: "Encomendas Ativas",
    total: "Total",
    submitOrderConfirm: "Enviar esta encomenda?",
    chooseProducts: "Escolhe produtos e quantidades",
    adminNoteLabel: "Mensagem para o cliente",
    adminNotePlaceholder: "Ex. Atrasado devido à produção do componente X...",
  },
  claims: {
    title: "Reclamações",
    fileClaim: "Apresentar Reclamação",
    editClaim: "Editar Reclamação",
    claimId: "ID Reclamação",
    orderId: "Encomenda",
    product: "Produto",
    reason: "Motivo",
    description: "Descrição",
    status: "Estado",
    resolution: "Resolução",
    pending: "Pendente",
    inProcess: "Em Processo",
    approved: "Aprovada",
    refused: "Recusada",
    noClaims: "Nenhuma reclamação",
    reasonLabel: "Motivo da Reclamação",
    descriptionLabel: "Descrição Detalhada",
    submitClaim: "Enviar Reclamação",
    claimFiled: "Reclamação apresentada com sucesso!",
    claimUnderReview: "A tua reclamação está em análise",
    claimResolved: "Reclamação resolvida",
    selectOrder: "Selecionar Encomenda",
    selectProduct: "Selecionar Produto",
    confirmResolution: "Resolução",
    myClaims: "As Minhas Reclamações",
  },
  client: {
    dashboardTitle: "Painel do Cliente",
    welcomeMessage: "Bem-vindo de volta",
    totalOrders: "Total Encomendas",
    pendingOrders: "Encomendas Pendentes",
    approvedOrders: "Encomendas Confirmadas",
    totalSpent: "Total Gasto",
    activeClaims: "Reclamações Ativas",
    recentOrders: "Encomendas Recentes",
    quickOrder: "Encomenda Rápida",
    viewHistory: "Ver Histórico",
    latestClaim: "Última Reclamação",
    myProfile: "O Meu Perfil",
  },
  demo: {
    title: "Experimenta a Demo",
    description:
      "Explora a plataforma sem criar conta. Escolhe um papel para começar instantaneamente.",
    adminLogin: "Entrar como Admin",
    adminDesc:
      "Acesso total para gerir clientes, encomendas, camiões, trabalhadores e produtos.",
    clientLogin: "Entrar como Cliente",
    clientDesc:
      "Experimenta a plataforma do ponto de vista de um cliente — faz encomendas, acompanha envios e mais.",
    selectClient: "Seleciona uma Empresa Demo",
    selectClientDesc:
      "Escolhe uma das empresas pré-carregadas para ver dados personalizados e histórico de encomendas.",
    loading: "A carregar contas demo...",
    noAccounts: "Nenhuma conta demo disponível",
    orStandardLogin: "Ou usa o início de sessão normal",
  },
  common: {
    loading: "A carregar...",
    error: "Algo correu mal",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    close: "Fechar",
    search: "Pesquisar",
    filter: "Filtrar",
    all: "Todos",
    actions: "Ações",
    confirm: "Confirmar",
    success: "Sucesso",
    warning: "Aviso",
    info: "Informação",
    yes: "Sim",
    no: "Não",
    back: "Voltar",
    next: "Seguinte",
    submit: "Enviar",
    reset: "Repor",
    noResults: "Sem resultados",
    pageNotFound: "Página não encontrada",
    goHome: "Ir para o Início",
    currencySymbol: "€",
    required: "Obrigatório",
    optional: "Opcional",
    status: "Estado",
    register: "Registar",
    signIn: "Iniciar Sessão",
    newer: "Mais recentes",
    older: "Mais antigos",
    today: "Hoje",
    yesterday: "Ontem",
  },
} as const;

export default strings;
export type Strings = typeof strings;
